[package]
name = "window"
version = "0.1.0"
authors = ["Yue Wu <wuyue16@pku.edu.cn>", "Wenqiu Yu <yuwenqiuj@gmail.com>"]
description = "an easy-to-use window object owned by application"
build = "../../build.rs"

[dependencies]
spin = "0.9.0"
owning_ref = { git = "https://github.com/theseus-os/owning-ref-rs" }
mpmc = "0.1.6"

[dependencies.log]
version = "0.4.8"

[dependencies.shapes]
path = "../../kernel/shapes"

[dependencies.color]
path = "../../kernel/color"

[dependencies.framebuffer_drawer]
path = "../framebuffer_drawer"

[dependencies.window_events]
path = "../window_events"

[dependencies.scheduler]
path = "../../kernel/scheduler"

[dependencies.framebuffer]
path = "../../kernel/framebuffer"

[dependencies.event_types]
path = "../../kernel/event_types"

[dependencies.spawn]
path = "../../kernel/spawn"

[dependencies.mouse]
path = "../../kernel/mouse"

[dependencies.path]
path = "../../kernel/path"

[lib]
crate-type = ["rlib"]
